---
- hosts: all
  remote_user: www-data
  tasks:
    # Jobs
    - name: 'Jobs: git repo'
      git:
        repo: https://github.com/devict/jobs.devict
        dest: /var/www/jobs
        force: yes

    - name: 'Jobs: .env file'
      template:
        src: ../files/jobs/env
        dest: /var/www/jobs/.env

    - name: 'Jobs: .db.env file'
      template:
        src: ../files/jobs/db.env
        dest: /var/www/jobs/.db.env

    - name: 'Jobs: systemd service definition'
      become: yes
      become_user: root
      template:
        src: ../files/jobs/jobs.service
        dest: /etc/systemd/system/jobs.service

    - name: 'Jobs: systemd service running'
      become: yes
      become_user: root
      systemd:
        daemon_reload: true
        name: jobs
        state: restarted
        enabled: true


