---
- hosts: all
  remote_user: www-data
  tasks:
    # VoteLocal
    - name: 'VoteLocal: git repo'
      git:
        repo: https://github.com/devict/votelocal
        dest: /var/www/votelocal
        force: yes

    - name: 'VoteLocal: .env file'
      template:
        src: ../files/votelocal/env
        dest: /var/www/votelocal/.env

    - name: 'VoteLocal: .db.env file'
      template:
        src: ../files/votelocal/db.env
        dest: /var/www/votelocal/.db.env

    - name: 'VoteLocal: .my.cnf file'
      template:
        src: ../files/votelocal/my.cnf
        dest: /var/www/votelocal/.my.cnf

    - name: 'VoteLocal: systemd service definition'
      become: yes
      become_user: root
      template:
        src: ../files/votelocal/votelocal.service
        dest: /etc/systemd/system/votelocal.service

    - name: 'VoteLocal: systemd scheduled jobs'
      become: yes
      become_user: root
      template:
        src: ../files/votelocal/votelocal-scheduled-jobs.service
        dest: /etc/systemd/system/votelocal-scheduled-jobs.service

    - name: 'VoteLocal: systemd scheduled jobs timer'
      become: yes
      become_user: root
      template:
        src: ../files/votelocal/votelocal-scheduled-jobs.timer
        dest: /etc/systemd/system/votelocal-scheduled-jobs.timer

    - name: 'VoteLocal: systemd DB backups'
      become: yes
      become_user: root
      template:
        src: ../files/votelocal/votelocal-backup.service
        dest: /etc/systemd/system/votelocal-backup.service

    - name: 'VoteLocal: systemd DB backups timer'
      become: yes
      become_user: root
      template:
        src: ../files/votelocal/votelocal-backup.timer
        dest: /etc/systemd/system/votelocal-backup.timer


    - name: 'VoteLocal: systemd service running'
      become: yes
      become_user: root
      systemd:
        daemon_reload: true
        name: votelocal
        state: restarted
        enabled: true

    - name: 'VoteLocal: post-restart operation'
      command:
        chdir: /var/www/votelocal
        cmd: docker-compose run --rm db mysql -e 'select 1;' votelocal

    - name: 'VoteLocal: systemd scheduled jobs running'
      become: yes
      become_user: root
      systemd:
        daemon_reload: true
        name: votelocal-scheduled-jobs.timer
        state: restarted
        enabled: true

    - name: 'VoteLocal: systemd DB backups running'
      become: yes
      become_user: root
      systemd:
        daemon_reload: true
        name: votelocal-backup.timer
        state: restarted
        enabled: true

