---
- hosts: all
  remote_user: www-data
  tasks:
    # VoteICT
    - name: 'VoteICT: git repo'
      git:
        repo: https://github.com/devict/voteict
        dest: /var/www/voteict
        force: yes

    - name: 'VoteICT: .env file'
      template:
        src: ../files/voteict/env
        dest: /var/www/voteict/.env

    - name: 'VoteICT: .db.env file'
      template:
        src: ../files/voteict/db.env
        dest: /var/www/voteict/.db.env

    - name: 'VoteICT: systemd service definition'
      become: yes
      become_user: root
      template:
        src: ../files/voteict/voteict.service
        dest: /etc/systemd/system/voteict.service

    - name: 'VoteICT: systemd service running'
      become: yes
      become_user: root
      systemd:
        daemon_reload: true
        name: voteict
        state: restarted
        enabled: true


